# ⚠️ QUAN TRỌNG: VẤN ĐỀ CẤP QUYỀN THƯ MỤC MOUNT
# 
# Khi sử dụng bind mount volumes, cần cấp quyền chính xác để tránh lỗi "Permission denied":
# 
# 1. THƯ MỤC CHA: /root/n8n-selfhost phải thuộc về user 1000 (ubuntu)
#    sudo chown -R ubuntu:ubuntu /root/n8n-selfhost
# 
# 2. THƯ MỤC MOUNT: ./n8n-data phải có quyền 755 và owner 1000:1000
#    sudo chown -R 1000:1000 n8n-data
#    chmod -R 755 n8n-data
# 
# 3. USER ID TRONG CONTAINER: Phải khớp với owner của thư mục mount
#    - N8N chạy với user 1000:1000
#    - PostgreSQL chạy với user 999:999 (postgres)
#    - Redis chạy với user 999:999 (redis)
# 
# 4. LỆNH CẤP QUYỀN HOÀN CHỈNH:
#    cd /root/n8n-selfhosted-docker
#    sudo chown -R ubuntu:ubuntu .
#    sudo chown -R 1000:1000 n8n-data
#    chmod -R 755 n8n-data
#
# ⚠️ KHÔNG BAO GIỜ mount thư mục root (/) vào container vì lý do bảo mật!
services:
  n8n:
    image: n8nio/n8n:1.107.4
    container_name: n8n
    restart: unless-stopped
    user: "1000:1000"  # Đảm bảo container chạy với user node
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=${N8N_HOST}     # giữ host anh đang dùng, chỉ thêm scheme
      - WEBHOOK_URL=${N8N_HOST}
      - N8N_WEBHOOK_URL=${N8N_HOST}
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_LOG_LEVEL=info
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_METRICS_ENABLED=false
      - N8N_USER_MANAGEMENT_DISABLED=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=AdminSecurePass2024
      - N8N_ENCRYPTION_KEY=581640c3852826913a434892d82834fd9fa80f940ac07691bd5908624902708c

      # Database (giữ nguyên hardcode)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=PostgresSecurePass2024

      # Redis (giữ nguyên hardcode cũ)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=RedisSecurePass2024

      # Queue mode (BỔ SUNG đúng biến Bull)
      - EXECUTIONS_MODE=queue
      - N8N_RUNNERS_ENABLED=false
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=false
      - QUEUE_BULL_PREFIX=n8n
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=RedisSecurePass2024
      - QUEUE_BULL_REDIS_DB=0  # BỔ SUNG: Chỉ định database Redis
      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200

      # Bật health endpoints cho readiness
      - QUEUE_HEALTH_CHECK_ACTIVE=true

      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=false
      - N8N_DISABLE_UI=false
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

    volumes:
      - n8n-data:/home/node/.n8n:rw  # Named volume: Tránh vấn đề permission
      - ./workflows:/home/node/.n8n/workflows:ro
      # 🔒 ĐÃ LOẠI BỎ: Docker socket mount vì không cần thiết và gây rủi ro bảo mật

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - n8n-network

    healthcheck:
      # dùng Node http client, không cần cài curl
      test: ["CMD-SHELL", "node -e \"require('http').get('http://localhost:5678/healthz/readiness',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))\""]
      interval: 30s
      timeout: 5s
      retries: 10

    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1

  n8n-worker:
    image: n8nio/n8n:1.107.4
    restart: unless-stopped
    user: "1000:1000"  # Đảm bảo container chạy với user node
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    entrypoint: ["node", "/usr/local/bin/n8n"]
    command: ["worker"]
    environment:
      - N8N_PORT=5678
      - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
      - N8N_LOG_LEVEL=info
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_METRICS_ENABLED=false

      # Queue worker - CẤU HÌNH QUAN TRỌNG
      - EXECUTIONS_MODE=queue
      - N8N_DISABLE_UI=true
      - N8N_DISABLE_PRODUCTION_MAIN_PROCESS=true
      - N8N_WORKER_MODE=true
      - N8N_RUNNERS_ENABLED=true  # BỔ SUNG: Bật task runners
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true  # BỔ SUNG: Offload manual executions

      # ĐỒNG BỘ ENCRYPTION KEY (BỔ SUNG)
      - N8N_ENCRYPTION_KEY=581640c3852826913a434892d82834fd9fa80f940ac07691bd5908624902708c

      # Database (giữ nguyên hardcode)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=PostgresSecurePass2024

      # Redis (Bull) — CẤU HÌNH QUEUE ĐẦY ĐỦ
      - QUEUE_BULL_PREFIX=n8n
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=RedisSecurePass2024
      - QUEUE_BULL_REDIS_DB=0  # BỔ SUNG: Chỉ định database Redis

      # Health endpoints
      - QUEUE_HEALTH_CHECK_ACTIVE=true

      - EXECUTIONS_TIMEOUT=3600
      - EXECUTIONS_TIMEOUT_MAX=7200

    volumes:
      - n8n-data:/home/node/.n8n:rw  # Named volume: Tránh vấn đề permission

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    networks:
      - n8n-network

    healthcheck:
      # Worker không có HTTP endpoint, kiểm tra process thay vì HTTP
      test: ["CMD-SHELL", "ps aux | grep 'n8n worker' | grep -v grep || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10

  cloudflared:
    build:
      context: .
      dockerfile: Dockerfile.cloudflared
    container_name: n8n-cloudflared
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - n8n-network
    depends_on:
      - n8n

  redis:
    image: redis:7-alpine
    container_name: n8n-redis
    restart: unless-stopped
    command: redis-server --requirepass RedisSecurePass2024 --maxmemory 512mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      - REDIS_PASSWORD=RedisSecurePass2024
    volumes:
      - redis-data:/data  # Named volume: Tránh vấn đề permission
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "RedisSecurePass2024", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  postgres:
    image: pgvector/pgvector:pg15
    container_name: n8n-postgres
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=PostgresSecurePass2024
      - POSTGRES_INITDB_ARGS=--locale=C.UTF-8
      - POSTGRES_SHARED_PRELOAD_LIBRARIES=vector
      - POSTGRES_MAX_CONNECTIONS=200
      - POSTGRES_SHARED_BUFFERS=256MB
      - POSTGRES_EFFECTIVE_CACHE_SIZE=1GB
      - POSTGRES_MAINTENANCE_WORK_MEM=64MB
      - POSTGRES_CHECKPOINT_COMPLETION_TARGET=0.9
      - POSTGRES_WAL_BUFFERS=16MB
      - POSTGRES_DEFAULT_STATISTICS_TARGET=100
      - POSTGRES_RANDOM_PAGE_COST=1.1
      - POSTGRES_EFFECTIVE_IO_CONCURRENCY=200
      - POSTGRES_WORK_MEM=8MB
      - POSTGRES_MIN_WAL_SIZE=1GB
      - POSTGRES_MAX_WAL_SIZE=4GB
      - POSTGRES_MAX_WORKER_PROCESSES=8
      - POSTGRES_MAX_PARALLEL_WORKERS_PER_GATHER=4
      - POSTGRES_MAX_PARALLEL_WORKERS=8
      - POSTGRES_MAX_PARALLEL_MAINTENANCE_WORKERS=4
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Named volume để tránh vấn đề permission
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 10

# Volumes section
volumes:
  n8n-data:  # Named volume cho N8N để tránh vấn đề permission
  redis-data:  # Named volume cho Redis để tránh vấn đề permission
  postgres-data:  # Named volume cho PostgreSQL để tránh vấn đề permission

networks:
  n8n-network:
    driver: bridge
    # Lưu ý: nếu trước đây anh để internal: true, hãy bỏ để cloudflared/n8n ra Internet.
